export const LOCATION_LIST_REQUEST = 'LOCATION_LIST_REQUEST'
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS'
export const LOCATION_LIST_FAIL = 'LOCATION_LIST_FAIL'

export const SINGLE_LOCATION_REQUEST = 'SINGLE_LOCATION_REQUEST'
export const SINGLE_LOCATION_SUCCESS = 'SINGLE_LOCATION_SUCCESS'
export const SINGLE_LOCATION_FAIL = 'SINGLE_LOCATION_FAIL'