export const PROGRAM_LIST_REQEST = "PROGRAM_LIST_REQEST"
export const PROGRAM_LIST_SUCCESS = "PROGRAM_LIST_SUCCESS"
export const PROGRAM_LIST_FAIL = "PROGRAM_LIST_FAIL"

export const SINGLE_PROGRAM_REQEST = "SINGLE_PROGRAM_REQEST"
export const SINGLE_PROGRAM_SUCCESS = "SINGLE_PROGRAM_SUCCESS"
export const SINGLE_PROGRAM_FAIL = "SINGLE_PROGRAM_FAIL"
